title: Future Lost
subtitle: A Dimm City Campaign
introduction: intro.md
stylesheet: game.css
options:
  difficulty: 0
  rollDuration: 3000
  dice:
    key: null
    name: 'Pink Dreams'
    category: 'Custom Sets'
    foreground: 'white'
    background: ['#ff007c', '#df73ff', '#f400a1', '#df00ff', '#ff33cc']
    outline: '#570000'
    texture: 'glass'
    description: 'Pink Dreams, for Ethan'
labels:
  introNextButtonText: 'Next'
  introBackButtonText: 'Back'
  introStartButtonText: 'Start'
  introExitButtonText: 'Exit'
  toolbarExitButtonText: 'Exit'
  journalEntryHeader: 'Record your journal entry'
  journalEntrySubHeader: 'Summary of events'
  journalEntryNextButtonText: 'Continue'
  journalEntrySaveButtonText: 'Record'
  journalEntryRestartButtonText: 'Restart'
  journalEntryExitButtonText: 'New Game'
  rollForTasksHeader: 'Roll for tasks'
  rollForTasksResultHeader: 'Click to continue'
  drawCardButtonText: 'Draw Card'
  successCheckHeader: 'Roll success check'
  successCheckResultHeader: 'Click to continue'
  failureCheckHeader: 'Failure Check'
  failureCheckLoss: 'The time machine has been damaged beyond repair'
  successCheckWin: 'You have managed to repair the time machine and are able to return home!'
  gameOverHeader: 'Game Over'
  gameOverButtonText: 'Record your final log'
  statusDisplayRoundText: 'Round: '
  healthMeterHeader: 'Health Meter'
  healthMeterSvg: null
  failureCounterHeader: 'Failure Counters'
  failureCounterSvg: null