title: Gnome Alone
subtitle: An example WAA based game
introduction: |
  # Gnome Alone
  
  ## Who

  You are Grimbol, a gnome of high spirits and even higher optimism. You were having the time of your life on a gnome party ship when a storm blew you overboard and shipwrecked you on an uncharted island. You are a genius tinkerer and your resourcefulness and optimism are your greatest tools. But the island is home to a terrifying, comically large predator that is very fond of gnome-sized snacks.

  ## What

  You must find a way off this island, building what you can with what the island has to offer, and avoiding the predator that stalks the landscape. The clock is ticking as you gather materials, build contraptions and maybe even tame local creatures to aid in your survival and eventual escape. A gnome's life is never dull, even when stranded on an island with a terrifying beast!

difficulty: 1

